version: '3.8'

services:
  db:
    image: mysql:8
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chatbot_db
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql

  backend:
    build: ./apps/backend
    container_name: backend
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: chatbot_db

  frontend:
    build: ./apps/frontend
    container_name: frontend
    restart: always
    volumes:
       - ./apps/frontend:/app
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: "http://backend:8000"

volumes:
  database:
